version: 2.1

parameters:
  run-15_API_Trigger-job:
    type: boolean
    default: false
  run_by_api:
    type: boolean
    default: false


jobs:
  regular:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run: echo "I was run normally"

  api-job:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run: echo "I was run by API"

workflows:
  15_API_Trigger:
    when: << pipeline.parameters.run-15_API_Trigger-job >>
    jobs:
      - regular

  api-workflow: #FIX , dont know how to do this at all really
    when: << pipeline.parameters.run_by_api >> # Without modifying the config, run api-job
    jobs:
      - api-job




# VS Code Extension Version: 1.5.0