version: 2.1

parameters:
  run-17_Executors-job:
    type: boolean
    default: false

jobs:
  build-docker:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - run: echo "docker executor"

workflows:
  17_Executors:
    when: << pipeline.parameters.run-17_Executors-job >>
    jobs:
      - build-docker




# VS Code Extension Version: 1.5.0