version: 2.1

parameters:
  run-04_Parallelism-job:
    type: boolean
    default: false

jobs:
  parallelism:
    docker:
      - image: cimg/base:2022.10
    parallelism: 2
    steps:
      - checkout
      # These two tests should run in parallel. Make it so!
      - run: 
          name: parallel
          command: |
            TEST=$(circleci tests glob "04_Parallelism/src/*.sh" | circleci tests split --split-by=timings)
            bash $TEST
      # - run:
      #     name: Run Hello test
      #     command: |
      #       bash 04_Parallelism/src/test_hello.sh
      # - run:
      #     name: Run Goodbye test
      #     command: |
      #       bash 04_Parallelism/src/test_goodbye.sh


workflows:
  04_Parallelism:
    when: << pipeline.parameters.run-04_Parallelism-job >>
    jobs:
      - parallelism


# VS Code Extension Version: 1.5.0