version: 2.1

setup: true


orbs:
  #continuation: circleci/continuation@0.3.1  #unsure why i would ever use this
  path-filtering: circleci/path-filtering@0.1.3


workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            01_Hello_World/.* run-01_Hello_World-job true
          base-revision: main
          config-path: 01_Hello_World/.circleci/config.yml
