version: 2.1

setup: true

#does not work
#https://github.com/CircleCI-Public/continuation-orb/issues/12


orbs:
  #continuation: circleci/continuation@0.3.1  #unsure why i would ever use this
  path-filtering: circleci/path-filtering@0.1.3


workflows:
  worlflow-picker:
    jobs:

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-01_Hello_World
      #     mapping: |
      #       01_Hello_World/.* run-01_Hello_World-job true
      #     config-path: 01_Hello_World/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-02_Yaml
      #     mapping: |
      #       02_Yaml/.* run-02_Yaml-job true
      #     config-path: 02_Yaml/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-03_Databases
      #     mapping: |
      #       03_Databases/.* run-03_Databases-job true
      #     config-path: 03_Databases/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-04_Parallelism
      #     mapping: |
      #       04_Parallelism/.* run-04_Parallelism-job true
      #     config-path: 04_Parallelism/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-05_Orbs
      #     mapping: |
      #       05_Orbs/.* run-05_Orbs-job true
      #     config-path: 05_Orbs/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-06_Caching
      #     mapping: |
      #       06_Caching/.* run-06_Caching-job true
      #     config-path: 06_Caching/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-07_Test_Summary
      #     mapping: |
      #       07_Test_Summary/.* run-07_Test_Summary-job true
      #     config-path: 07_Test_Summary/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-08_Branch_filters
      #     mapping: |
      #       08_Branch_filters/.* run-08_Branch_filters-job true
      #     config-path: 08_Branch_filters/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-09_Tag_filters
      #     mapping: |
      #       09_Tag_filters/.* run-09_Tag_filters-job true
      #     config-path: 09_Tag_filters/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-10_Workflow_Fan_out
      #     mapping: |
      #       10_Workflow_Fan_out/.* run-10_Workflow_Fan_out-job true
      #     config-path: 10_Workflow_Fan_out/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-11_Workflow_Sequential
      #     mapping: |
      #       11_Workflow_Sequential/.* run-11_Workflow_Sequential-job true
      #     config-path: 11_Workflow_Sequential/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-12_Matrix_Builds
      #     mapping: |
      #       12_Matrix_Builds/.* run-12_Matrix_Builds-job true
      #     config-path: 12_Matrix_Builds/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-13_Workspaces
      #     mapping: |
      #       13_Workspaces/.* run-13_Workspaces-job true
      #     config-path: 13_Workspaces/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-14_Conditional_Logic
      #     mapping: |
      #       14_Conditional_Logic/.* run-14_Conditional_Logic-job true
      #     config-path: 14_Conditional_Logic/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-15_API_Trigger
      #     mapping: |
      #       15_API_Trigger/.* run-15_API_Trigger-job true
      #     config-path: 15_API_Trigger/.circleci/config.yml

      - path-filtering/filter:
          base-revision: main
          name: check-updated-files-16_Reusable_config
          mapping: |
            16_Reusable_config/.* run-16_Reusable_config-job true
          config-path: 16_Reusable_config/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-17_Executors
      #     mapping: |
      #       17_Executors/.* run-17_Executors-job true
      #     config-path: 17_Executors/.circleci/config.yml

      # - path-filtering/filter:
      #     base-revision: main
      #     name: check-updated-files-18_Runners
      #     mapping: |
      #       18_Runners/.* run-18_Runners-job true
      #     config-path: 18_Runners/.circleci/config.yml

