version: 2.1

parameters:
  run-05_Orbs-job:
    type: boolean
    default: false

orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  orbs:
    docker:
      - image: cimg/base:2019.10 #does not work with 2022.10
    steps:
      - checkout
      - ruby/install:
          version: 2.6.3
      # Add step below to install Ruby version 2.6.3      
      - run: ruby -v




workflows:
  05_Orbs:
    when: << pipeline.parameters.run-05_Orbs-job >>
    jobs:
      - orbs


