version: 2.1

parameters:
  run-11_Workflow_Sequential-job:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run: echo "Building complete"
  test:
    docker:
      - image: cimg/base:2022.10
    steps:
      - run: echo "Testing complete"
  deploy:
      docker:
        - image: cimg/base:2022.10
      steps:
        - run: echo "DEPLOYING" # Make sure tests pass first!

workflows:
  11_Workflow_Sequential:
    when: << pipeline.parameters.run-11_Workflow_Sequential-job >>
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test






# VS Code Extension Version: 1.5.0