version: 2.1

parameters:
  run-14_Conditional_Logic-job:
    type: boolean
    default: false
  condition-workflow:
    type: boolean
    default: true

jobs:
  my-job:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - when:
          condition:
            # Add condition to execute this step when the github branch is equal to 'main' #FIX , dont know how to do
          steps:
            - run: echo "I am on main"

  conditional-job:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run: echo "This ran on a pipeline parameter"

workflows:
  14_Conditional_Logic:
    when: << pipeline.parameters.run-14_Conditional_Logic-job >>
      and: << pipeline.parameters.condition-workflow >>
    jobs:
      - my-job
      - conditional-job

  # conditional-workflow:
  #   when:
  #       # Add condition to execute this workflow when condition-workflow is equal to true
  #   jobs:



# VS Code Extension Version: 1.5.0