version: 2.1

parameters:
  run-09_Tag_filters-job:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run: echo "Building complete"
  test:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run: echo "Testing complete"
  deploy:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run: echo "Deploy complete"

workflows:
  version: 2 #do i even need this?
  09_Tag_filters:
    when: << pipeline.parameters.run-09_Tag_filters-job >>
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^beta.*/
      - test:
          requires:
            - build
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^beta.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^beta.*/

