version: 2.1

parameters:
  run-08_Branch_filters-job:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run: echo "Building complete"
  test-production:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run: echo "Testing complete"
  deploy:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run: echo "Deploy complete"

workflows:
  08_Branch_filters:
    when: << pipeline.parameters.run-08_Branch_filters-job >>
  # version: 2
    jobs:
      - build
      - test-production:
          requires:
            - build
      - deploy:
          requires:
            - test-production
          filters:
            branches:
              only:
                - main #aka production in the OG request
                # - 08_branch_filters_production #aka production in the OG request




# VS Code Extension Version: 1.5.0