version: 2.1

setup: true


orbs:
  path-filtering: circleci/path-filtering@0.1.3


workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: main
          name: check-updated-files
          mapping: |
            01_Hello_World/.* run-01_Hello_World-job true
            02_Yaml/.* run-02_Yaml-job true
          config-path: .circleci/continue_config.yml

          
