version: 2.1

parameters:
  run-06_Caching-job:
    type: boolean
    default: false

jobs:
  caching:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      # Uncomment below and set the key to point to the proper file
      - restore_cache:
          name: Restore Yarn Package Json Cache
          keys: yarn-packages-v1-{{ checksum "06_Caching/package.json" }}      
          keys: yarn-packages-v1-      
      - run:
          name: Install Dependencies
          command: cd 06_Caching/ && yarn install --immutable && pwd && ls
      # Uncomment below and set the key to point to the proper file
      - save_cache:
          name: Save Yarn Package Json Cache
          key: yarn-packages-v1-{{ checksum "06_Caching/package.json" }}
          paths:
            - .yarn/cache

workflows:
  06_Caching:
    when: << pipeline.parameters.run-06_Caching-job >>
    jobs:
      - caching

