version: 2.1

parameters:
  run-02_Yaml-job:
    type: boolean
    default: false


jobs:
  Yaml:
    docker: 
      - image: cimg/base:2022.10 # the primary container, where your job's commands are run
    steps:
      - checkout
      - run:
          name: "'run' statements can actually contain a 'name' and 'command' argument as well"
          command: | 
            echo "You can even have multiline commands."
      - restore_cache:
          keys:
          - v1-dependencies-
      - run: if [[ ! -e ~/cache/ ]] ; then mkdir ~/cache/ ; fi
      - run: echo "testfile" > ~/cache/log.txt
      - save_cache:
          key: v1-dependencies-
          paths: ~/cache




workflows:
  02_Yaml:
    when: << pipeline.parameters.run-02_Yaml-job >>
    jobs:
      - Yaml

